language: node_js
sudo: false
dist: trusty
node_js:
- 8
- 7
- 6
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn add rxjs --peer --ignore-scripts
script: yarn run test:cover
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
